### ISSUE TITLE
Links should be supported in comment blocks

### ISSUE THREAD

**Issue by lucasvickers** [gregkepler/Cinder#33]
I argue that we should support the ability to link external webpages from comment blocks.  For my use case, please see below.

```
    /** \brief Creates a rotating log file that will rotate when the first logging event occurs
     * after midnight.
     *
     * File appending is configurable via \a appendToExisting.  \a formatStr will be passed to
     * [strtime](http://www.cplusplus.com/reference/ctime/strftime/) to determine the file name.
     * The log file will then be created in the folder defined in the \a folder parameter.
     * If \a folder or \a formatStr are empty, the request will be ignored.
     */
```

Evaluated to the following:
![screen shot 2015-09-06 at 1 37 22 pm](https://cloud.githubusercontent.com/assets/1099950/9705730/6ff5839e-549c-11e5-87dc-0d08c10b3863.png)

Thanks!

**Comment by gregkepler** [comment]
Thanks for finding that missing feature. Should be fixed now.

There may be more missed tag parsing issues as the doxygen markup parsing was one of the first things done. Probably needs a refactoring in itself.
