### ISSUE TITLE
The \p and \param commands do not work

### ISSUE THREAD

**Issue by lucasvickers** [gregkepler/Cinder#34]
I think it would be a nice to have.  I see guys are resorting to `\a` right now, which I guess does the job, but I suspect if we get `\p` support working it could leave us with more options in the future.

**Comment by gregkepler** [comment]
\p is now supported via 492e0b20082b6126ffde022393dd0ebaa21aed72

We'll have to go back and determine how we want the \param elements to be displayed in the descriptions. I'll open a new issue for that. In the meantime, I'd say document the code how you think it should be documented and we'll figure out how it should be displayed on the docs site side.

**Comment by gregkepler** [comment]
Opened an issue specifically for \param support (#35)
