### ISSUE TITLE
Guide folder path is incorrect

### ISSUE THREAD

**Issue by lucasvickers** [gregkepler/Cinder#36]
https://github.com/gregkepler/Cinder/blob/doxNext/docs/htmlsrc/guides/docs/documenting_cinder.html#L177

This line should read `docs/htmlsrc/guides` not `docs/guides`

I tried to do a PR, but having some problems -- it's minor enough I'm just making it an issue, sorry.

Thansk

**Comment by gregkepler** [comment]
Weird that a PR wasn't working. I may have to rebase on the latest cinder dev branch. 

I'll add this to a slew of updates that I need to make to the documentation guides.

Thanks.

**Comment by lucasvickers** [comment]
Thanks.  the PR issue could be 100% me.
