### ISSUE TITLE
Long function comments are truncated in html

### ISSUE THREAD

**Issue by lucasvickers** [gregkepler/Cinder#40]
I can see @andrewfb saying this is too long for in-code documentation, but I do feel it's useful to explain the details of the parameters in code -- and this is a particularly complex function.

```
    //! \brief Creates a rotating log file that will rotate when the first logging event occurs
    //! after midnight.
    //!
    //! File appending is configurable via \p appendToExisting.  \p formatStr will be passed to
    //! [strtime](http://www.cplusplus.com/reference/ctime/strftime/) to determine the file name.
    //! The log file will then be created in the folder defined in the \p folder parameter.
    //! If \p folder is empty, uses the folder where the binary is located.  If the folder structure
    //! defined in \p folder does not exist, it will be created.
    //! If \p formatStr is empty, an assertion will be thrown.
    LoggerFileRotating( const fs::path &folder, const std::string &formatStr, bool appendToExisting = true );
```

In html I see
![screen shot 2015-09-13 at 4 04 56 pm](https://cloud.githubusercontent.com/assets/1099950/9838679/3411396e-5a31-11e5-85b0-1222b2fd90c4.png)

**Comment by andrewfb** [comment]
This definitely appears to be a bug in the docs system. However it brings up an interesting point too. Currently we don't take advantage of the \brief command in any particular way, simply concatenating the rest of the documentation to its output. It would be reasonable to assume that it's simply no-op meta information that might be handy if we ever change the design of the docs. However I think it can complicate documenting things in some instances. Specifically, it requires you to create a coherent brief description that reads comprehensibly on its own, and then the additional sentences must feel natural when appended to the brief one. An example:

```
//! \brief LoggerFile will write log messages to a specified file.
//!
//! LoggerFile will write to a specified file, either appending to or overwriting that
//! file at application startup.
```

Those two sentences make sense when separated, but are awkward when concatenated, as they will be in the current system. The most natural phrasing would probably be something like, "LoggerFile will write log messages to a specified file. It either appends or overwrites that file at startup." As an additional point, \brief doesn't really lead to more legible documentation for cases where it's being read inline in the .h itself, rather than the HTML docs.

Unlike some of the other Doxygen commands, \brief feels like one we need a binary policy decision on to me. I'm obviously open to other opinions but my instinct would be to simply stop using it.

**Comment by lucasvickers** [comment]
Agreed.  It also promotes longer comments (in terms of number of lines).  If we had something explicit already planned for `\brief` then we should keep it, but it seems right now it's only going to cause confusion.

I'll update my Cinder [PR](https://github.com/cinder/Cinder/pull/1112) to reflect the decision.

**Comment by richardeakin** [comment]
Concerning the usage of `\brief`, I might be missing something, but is there any other way to get the one liner separated from detailed docs in doxygen xml output? I'm not sure exactly how this maps in the new system, but what I mean is that currently `ci::audio::Node` looks like this in the `ci::audio::` namespace overview:

<img width="1021" alt="screenshot 2015-09-15 02 45 48" src="https://cloud.githubusercontent.com/assets/5132127/9869732/5535bbb4-5b54-11e5-844b-ca0b1013f4fb.png">

If I remove the `\brief` command, then the same area looks like:

<img width="1020" alt="screenshot 2015-09-15 02 47 25" src="https://cloud.githubusercontent.com/assets/5132127/9869741/6484279a-5b54-11e5-8f53-88af03099d8b.png">

To me, a brief doc line versus detailed info is important when looking at an overview of a group of methods and / or classes, a small price to pay for the extra dox tag (`\brief). To take Lucas' example, you'd only show the sentence "Creates a rotating log file that will rotate when the first logging event occurs after midnight." on the function overview list, and if you clicked on that function then you'd be directed to more detailed information.

Greg and I were kicking around if there were a different way to generate that one liner, like perhaps just take the first sentence of the doc block?

Lastly I'm not sure why using `\brief` needs to be binary, if it is omitted then the entire doc line is taken to be used for both brief and / or detailed info.  It's main purpose is to allow you to do what I just described, which is get at a one liner so you don't clutter up an overview page.

**Comment by gregkepler** [comment]
As of right now, I'm not doing anything specifically with the brief descriptions, so I don't see a need for it at the moment. Though, I'd hate to be limited in case be do want to use if for something like tools tips in the future or something. M

aybe the rule should be that if you are going to use it, write it in a way that it serves both one its own and as a first sentence of the full description. If you don't write one, then that's ok too. I'll always show the brief description and full descriptions concatenated in the meantime.

would that work for everyone?

Also, to throw another wrench in there, the QT_AUTOBRIEF option is set to true in Doxygen right now, which automatically creates a brief description from the first line.

**Comment by lucasvickers** [comment]
> Maybe the rule should be that if you are going to use it, write it in a way that it serves both one its own  and as a first sentence of the full description. If you don't write one, then that's ok too. I'll always show  the brief description and full descriptions concatenated in the meantime.

I don't think that works because if down the road we use `\brief` for something entirely different (like mouse over tips), we wouldn't keep backwards compatibility.

> Also, to throw another wrench in there, the QT_AUTOBRIEF option is set to true in Doxygen right now, which automatically creates a brief description from the first line.

In that case, I think we need to add that information into the code comment guidelines.  It means we're getting the brief right now w/o dealing w/ an explicit `\brief` tag.  I think this means we just move forward writing the first sentence as the brief, but make sure it flows.  The first sentence should be written this way anyway.  If we want to do something like a mouse over sentence in the future we can work it out then.

**Comment by andrewfb** [comment]
OK - after discussing this some more in Rich, I think we'll standardize on the policy of **not** using \brief for functions, but it's optional for classes. While we don't use it right now, hypothetically in the future we might in the class list of the namespace pages. If a class does have a \brief, this \brief would not be echoed in the class-specific page. This is to address what we were discussing above, namely that it's often awkward to force a sentence to serve double-duty as both a summary and as the opening of a paragraph. Consequently \brief is a no-op for classes for the time being, but probably a good habit, and is disallowed for member functions. We should rectify this for any existing \briefs in functions soon. And all of this is pending Greg's agreement and relevant updates to the Python code.

**Comment by gregkepler** [comment]
Consider me agreed. I'll make sure that this is taken into account in the next day or so. I'll also add this policy to the Documenting Cinder guide.

**Comment by lucasvickers** [comment]
Sounds good, works for me as well.

**Comment by gregkepler** [comment]
Fyi, I was looking into this a bit today and learned that doxygen automatically places \brief text that breaks onto a new line as part of the detailed description.

This:

```
//! \brief Creates a rotating log file that will rotate when the first logging event occurs
//! after midnight.
```

Turns into this:

```
<briefdescription>
<para>Creates a rotating log file that will rotate when the first logging event occurs. </para>              
</briefdescription>
<detaileddescription>
<para>after midnight.</para><para>File appending is configurable via 
...
</detaileddescription>
```

So best keep the brief descriptions brief

**Comment by gregkepler** [comment]
@lucasvickers I think I fixed this truncation issue recently with another bug fix. Take a look and see if it's still an issue for you.

**Comment by lucasvickers** [comment]
The extra-long comment truncation does appear to be fixed.  Sorry for the delay.

Thanks for the heads up on the \brief line brakes.
